ENCODER_DIR="bidirectional"
ENCODER_TYPE="lstm"

./command.sh RECORD_AUDIO $ENCODER_DIR $ENCODER_TYPE
./command.sh READ_CONTACTS $ENCODER_DIR $ENCODER_TYPE
./command.sh ACCESS_FINE_LOCATION $ENCODER_DIR $ENCODER_TYPE
./command.sh READ_CALENDAR $ENCODER_DIR $ENCODER_TYPE
./command.sh CAMERA $ENCODER_DIR $ENCODER_TYPE
./command.sh READ_SMS $ENCODER_DIR $ENCODER_TYPE
./command.sh READ_CALL_LOGS $ENCODER_DIR $ENCODER_TYPE
./command.sh CALL_PHONE $ENCODER_DIR $ENCODER_TYPE
./command.sh WRITE_SETTINGS $ENCODER_DIR $ENCODER_TYPE
./command.sh GET_TASKS $ENCODER_DIR $ENCODER_TYPE
